Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true


### DB vm  ####
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "bento/ubuntu-22.04-arm64"
    jenkins.vm.hostname = "db01"
    jenkins.vm.network "private_network", ip: "192.168.56.25"
    jenkins.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = true
      vmware.allowlist_verified = true
      vmware.memory = "2048"
      vmware.cpus = "1"
    end
  end

### Memcache vm  ####
  config.vm.define "sonarqube" do |sonarqube|
    sonarqube.vm.box = "bento/ubuntu-22.04-arm64"
    sonarqube.vm.hostname = "mc01"
    sonarqube.vm.network "private_network", ip: "192.168.56.24"
    sonarqube.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = true
      vmware.allowlist_verified = true
      vmware.memory = "1024"
      vmware.cpus = "1"

    end
  end

### RabbitMQ vm  ####
  config.vm.define "nexus" do |nexus|
    nexus.vm.box = "bento/ubuntu-22.04-arm64"
    nexus.vm.hostname = "rmq01"
    nexus.vm.network "private_network", ip: "192.168.56.23"
    nexus.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = true
      vmware.allowlist_verified = true
      vmware.memory = "2048"
      vmware.cpus = "1"
    end
  end
end
