Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true


### DB vm  ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "spox/ubuntu-arm"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.25"
    db01.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = true
      vmware.allowlist_verified = true
      vmware.memory = "600"
      vmware.cpus = "1"
    end
  end

### Memcache vm  ####
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "spox/ubuntu-arm"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.24"
    mc01.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = true
      vmware.allowlist_verified = true
      vmware.memory = "600"
      vmware.cpus = "1"

    end
  end

### RabbitMQ vm  ####
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "spox/ubuntu-arm"
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.23"
    rmq01.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = true
      vmware.allowlist_verified = true
      vmware.memory = "600"
      vmware.cpus = "1"
    end
  end

### tomcat vm ###
  config.vm.define "app01" do |app01|
    app01.vm.box = "spox/ubuntu-arm"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.22"
    app01.vm.provider "vmware_desktop" do |vb|
     vb.memory = "1024"
     vb.gui = true
     vb.allowlist_verified = true
     vb.cpus = "1"
    end
  end


### Nginx VM ###
  config.vm.define "web01" do |web01|
   # web01.vm.disk :disk, size: "10GB", primary: true
    web01.vm.box = "spox/ubuntu-arm"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.21"
    web01.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = true
      vmware.allowlist_verified = true
      vmware.memory = "800"
      vmware.cpus = "1"
    end

  end

end
